[package]
name = "ex2-surface"
version = "0.1.0"
authors = [
    "Jeremy L Thompson <jeremy@jeremylt.org>",
]
edition = "2018"

[dependencies]
structopt = { version = "0.3", default-features = false }
libceed = { path = "../../../libCEED/rust/libceed" }
mesh = { path = "../mesh" }
